### ISSUE TITLE
Better structure of unit tests

### ISSUE THREAD

**Issue by der-michik** [der-michik/c3bottles#56]
Instead of having a single monolithic `test_model.py`, we should have a more modular and flexible test structure and the tests should not only cover the model but also the views etc.

**Comment by jelly** [comment]
Maybe a separate tests dir with a test per model as in:
```
tests/test_Droppoint.py
tests/test_Report.py
```

I could make a PR for this.

**Comment by der-michik** [comment]
That was exactly what I was thinking about. I would even go a step further and reproduce the complete module structure under tests/ as at some point we might test views etc. as well.
