### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by pintman** [der-michik/c3bottles#70]
After creating a new user as mentioned in the installation information, the user ist not able to login:

  "Login failed!" - "Wrong user name or password."

**Comment by pintman** [comment]
Some further investigations show that it seems  the user can not be fetched from the database in view/user.py: User.get(forms.username.data) finds no user.

**Comment by der-michik** [comment]
That worked when I added it on my laptop, but now on my desktop I can reproduce your problem. Normally that shouldn't happen.
