### ISSUE TITLE
Due date is too late for SHA2017

### ISSUE THREAD

**Issue by sebastius** [der-michik/c3bottles#74]
Hi, i'd really love to use these features but the date for this milestone are way way to late for me to work with in preparation for SHA.

June 30 is my personal deadline, after that i have less than a week to prepare the system for deployment to SHA2017.

**Comment by der-michik** [comment]
Ok, I set a due date like I would do for Congress. I changed it now. :)

I will hopefully be able to do some stuff in the train to the GPN next week.
